### Login user
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "12345678"
}

### Register user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "name": "Test User",
    "email": "testuser@example.com",
    "password": "12345678",
    "role_id": 1
}

### profile
GET http://localhost:8080/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJyb2xlIjoibWFuYWdlciIsInN1YiI6ImFjY2VzcyIsImV4cCI6MTc1ODYxMzkwMiwiaWF0IjoxNzU4NTI3NTAyfQ.TiZuV5FUpTprgTlAffa8cyjQKEFF8y0M4JlUJKS9uxo
